### PR TITLE
Update

### PR DESCRIPTION
**Pull request by SimonBiggs**
Is it worth working in the same repo? Or would it be better for me to do this prototyping parallel in a separate repo?

### CODE REVIEW

**Comment by darcymason** [comment]
> Is it worth working in the same repo? Or would it be better for me to do this prototyping parallel in a separate repo?

I was going to ask you the same question.  I think your jax work being in the repo isn't needed for the transpiling part - I can keep an eye on the developments and we can communicate needs - but what do you think of the other way around?  The *output* of the transpiler code might help you, but not necessarily the transpiler code itself, right?

**Comment by SimonBiggs** [comment]
> The output of the transpiler code might help you, but not necessarily the transpiler code itself, right?

Yup, certainly. Any ideas?

**Comment by darcymason** [comment]
> Yup, certainly. Any ideas?

I think separately for now if that's not too much trouble.  Let's see where both of these go and revisit it later.

**Comment by SimonBiggs** [comment]
Yup, good plan. Will do.

**Pull request closed without merging**
